### ISSUE TITLE
[AVM Module Issue]: Add support for network rule (even if not in Premium SKU)

### ISSUE THREAD

**Issue by gregbaleyy** [Azure/terraform-azurerm-avm-res-servicebus-namespace#34]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Network rule can be used even if SKU is not Premium but the AVM Module forbid it.

Reference : [service-bus-ip-filtering](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-ip-filtering#important-points)

> Virtual Networks are supported only in the premium tier of Service Bus. **If upgrading to the premium tier isn't an option, it's possible to use IP firewall rules.** We recommend that you keep the Shared Access Signature (SAS) token secure and share it with only authorized users. For information about SAS authentication, see [Authentication and authorization](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-authentication-and-authorization#shared-access-signature).

**Comment by gregbaleyy** [comment]
@bryansan-msft

**Comment by bryansan-msft** [comment]
Hello @gregbaleyy, I have been out for a month. I will have a look at this during this week
