### ISSUE TITLE
[AVM Module Issue]: Could not retrieve the list of available versions for provider hashicorp/modtm. Provider Not Found

### ISSUE THREAD

**Issue by Girish-Maddineni** [Azure/terraform-azurerm-avm-res-servicebus-namespace#44]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

 Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/modtm:
provider registry registry.terraform.io does not have a provider named registry.terraform.io/hashicorp/modtm

 Did you intend to use azure/modtm? If so, you must specify that source address in each
module which requires that provider. To see which modules are currently depending on
hashicorp/modtm, run the following command:
     `terraform providers`
exit status 1
```

terraform --version

Terraform v1.7.5
on darwin_amd64
```

**Output of terraform providers,**

Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/azuread]
├── provider[registry.terraform.io/hashicorp/azurerm] >= 3.63.0, < 4.0.0
├── **provider[registry.terraform.io/azure/modtm] 0.3.2**
├── module.naming
│   └── provider[registry.terraform.io/hashicorp/random] >= 3.3.2
├── module.service_bus
│   ├── provider[registry.terraform.io/hashicorp/random] ~> 3.6
│   ├── provider[registry.terraform.io/hashicorp/azurerm] ~> 3.71
│   └── **provider[registry.terraform.io/hashicorp/modtm]**
└── module.this

**Expected Behaviour:** 

Module should have a Required provider for modtm that being used in telementary and it looks like, 

```
terraform {
  required_version = "~> 1.5"

  required_providers {

    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.71"
    }

    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }

    modtm = {
      source = "Azure/modtm"
      version = "0.3.2"
  }
 }
}
```

since it's not defined, by default it's looking in hashicorp registry (where it is not located)

**Comment by davenicoll** [comment]
I've implemented the necessary changes. Should be a quick review. Can you take a look please @bryansan-msft @matt-FFFFFF @mbilalamjad

**Comment by matt-FFFFFF** [comment]
LGTM
